defaults: &defaults
  # The email's sender address.
  sender: paul.e.jolley@gmail.com
  
  # Outgoing email configuration
  # Taken from Teambox's config file
  smtp_settings:
    :domain:         Hublix.com       # the domain your emails will come from
    :address:        smtp.google.com  # SMTP server used to send emails
    :port:           587
    :authentication: :yes
    :user_name:        
    :password:       

    # Set to true when using Gmail
    :enable_starttls_auto: true

    # Set to true if you have Net::SMTPSyntaxError errors when sending email.
    # Rails has sometimes a problem when sending email from "Name <address@host.com>".
    # If you are having problems sending email and your host is correctly configured,
    # try setting safe_from to true. You may need to create a user account for no-reply@yourapp.com
    :safe_from: false

development:
  <<: *defaults

test: &testing
  <<: *defaults